#!/usr/bin/env bash

# Compiles + runs the program.

docker_image_name="ccdl"

docker build --rm . -t $docker_image_name 

if [[ "$?" != "0" ]]; then
    echo "Failed to build Docker container."
    exit 1
fi

# note: dev_testing_net is the Docker network where my local MySQL DB is running
# todo: Set up a separate MySQL container which runs on the default Docker network so this doesn't need
# to be specified. I'm not sure how it behaves if this network doesn't exist.
docker run --interactive --tty --network dev_testing_net --env-file .env $docker_image_name

if [[ "$?" != "0" ]]; then
    echo "Failed to run Docker container."
    exit 1
fi