#!/usr/bin/env bash

# Compiles + runs the program.

docker_image_name="ccdl"

docker build --rm . -t $docker_image_name 

if [[ "$?" != "0" ]]; then
    echo "Failed to build Docker container."
    exit 1
fi

docker run --network dev_testing_net --env-file .env $docker_image_name

if [[ "$?" != "0" ]]; then
    echo "Failed to run Docker container."
    exit 1
fi